### PR TITLE
Fixing issue #54 for Error: Unknown command 'Build-Assembly'.

### PR DESCRIPTION
**Pull request by tahazayed**
when you build using  Cake-Build.bat I have received this error

Error: Unknown command 'Build-Assembly'.

       build\build.cake -target=Build-Assembly -configuration=Release -verbosity=Verbose
                                ^^^^^^^^^^^^^^ No such command

solution source [cake-cli-updates](https://cakebuild.net/docs/getting-started/upgrade#cake-cli-updates)

Fixing issue #54

### CODE REVIEW

**Review by ltrzesniewski — COMMENTED** [review]
This change works, but I'd rather take the opportunity to update the file to [the latest version](https://github.com/cake-build/resources/blob/master/dotnet-framework/build.ps1).

**Comment by tahazayed** [comment]
@ltrzesniewski done, updated to the latest version

**Comment by tahazayed** [comment]
@ocoanet would you please review this pull request?

**Comment by ocoanet** [comment]
LGTM, thank you for the PR!

**Pull request merged**
